import type { Category, Word } from "@/app/_game/types";

export const categories: Category[] = [
  { id: "comida", name: "Comida", enabled: true },
  { id: "animales", name: "Animales", enabled: true },
  { id: "objetos", name: "Objetos cotidianos", enabled: true },
  { id: "peliculas-series", name: "Peliculas / series", enabled: true },
  { id: "lugares", name: "Lugares", enabled: true },
  { id: "profesiones", name: "Profesiones", enabled: true },
  { id: "personas-famosas", name: "Personas famosas", enabled: true },
  { id: "xvip", name: "XVIP", enabled: true },
  { id: "futbolistas", name: "Futbolistas", enabled: true },
];

const valuesByCategory: Record<string, string[]> = {
  comida: [
    "pizza",
    "hamburguesa",
    "tortilla",
    "paella",
    "sushi",
    "taco",
    "burrito",
    "ensalada",
    "sopa",
    "gazpacho",
    "croqueta",
    "empanada",
    "pasta",
    "lasana",
    "arroz",
    "pan",
    "queso",
    "jamon",
    "chocolate",
    "helado",
    "galleta",
    "bizcocho",
    "flan",
    "yogur",
    "manzana",
    "platano",
    "naranja",
    "sandia",
    "melon",
    "fresa",
    "uva",
    "pera",
    "kiwi",
    "zanahoria",
    "patata",
    "tomate",
    "lechuga",
    "cebolla",
    "ajo",
    "pimiento",
    "pollo",
    "ternera",
    "pescado",
    "atun",
    "salmon",
    "huevo",
    "lentejas",
    "garbanzos",
    "cereal",
    "cafe",
    "te",
    "zumo",
  ],
  animales: [
    "perro",
    "gato",
    "caballo",
    "vaca",
    "cerdo",
    "oveja",
    "cabra",
    "gallina",
    "pato",
    "conejo",
    "raton",
    "hamster",
    "tortuga",
    "pez",
    "delfin",
    "ballena",
    "tiburon",
    "pulpo",
    "cangrejo",
    "medusa",
    "leon",
    "tigre",
    "elefante",
    "jirafa",
    "cebra",
    "mono",
    "gorila",
    "oso",
    "lobo",
    "zorro",
    "ciervo",
    "camello",
    "koala",
    "canguro",
    "panda",
    "aguila",
    "buho",
    "loro",
    "pinguino",
    "flamenco",
    "serpiente",
    "cocodrilo",
    "rana",
    "abeja",
    "mariposa",
    "hormiga",
    "arana",
    "mosquito",
    "caracol",
    "murcielago",
    "erizo",
    "mapache",
  ],
  objetos: [
    "telefono",
    "llaves",
    "cartera",
    "mochila",
    "boligrafo",
    "lapiz",
    "cuaderno",
    "libro",
    "mesa",
    "silla",
    "sofa",
    "cama",
    "almohada",
    "manta",
    "lampara",
    "reloj",
    "espejo",
    "cepillo",
    "toalla",
    "jabon",
    "botella",
    "vaso",
    "taza",
    "plato",
    "tenedor",
    "cuchillo",
    "cuchara",
    "sarten",
    "olla",
    "nevera",
    "microondas",
    "lavadora",
    "televisor",
    "mando",
    "auriculares",
    "cargador",
    "ordenador",
    "raton",
    "teclado",
    "paraguas",
    "zapatos",
    "camiseta",
    "chaqueta",
    "gorra",
    "gafas",
    "maleta",
    "bicicleta",
    "pelota",
    "vela",
    "caja",
    "tijeras",
    "cinta",
  ],
  "peliculas-series": [
    "Titanic",
    "Avatar",
    "Matrix",
    "Gladiator",
    "Jurassic Park",
    "Star Wars",
    "Indiana Jones",
    "Harry Potter",
    "El Rey Leon",
    "Toy Story",
    "Frozen",
    "Buscando a Nemo",
    "Shrek",
    "Coco",
    "Up",
    "Los Increibles",
    "Batman",
    "Superman",
    "Spider-Man",
    "Iron Man",
    "Los Vengadores",
    "Black Panther",
    "Doctor Who",
    "Friends",
    "The Office",
    "Breaking Bad",
    "Stranger Things",
    "La Casa de Papel",
    "Los Simpson",
    "Futurama",
    "Juego de Tronos",
    "The Mandalorian",
    "Sherlock",
    "Lost",
    "Dark",
    "The Crown",
    "Narcos",
    "Peaky Blinders",
    "The Last of Us",
    "Wednesday",
    "Dune",
    "Rocky",
    "Grease",
    "Jumanji",
    "Forrest Gump",
    "Casablanca",
    "El Padrino",
    "El Señor de los Anillos",
    "Piratas del Caribe",
    "Mision Imposible",
    "Regreso al Futuro",
    "Cazafantasmas",
  ],
  lugares: [
    "playa",
    "montana",
    "bosque",
    "desierto",
    "isla",
    "rio",
    "lago",
    "cueva",
    "volcan",
    "ciudad",
    "pueblo",
    "barrio",
    "parque",
    "plaza",
    "mercado",
    "supermercado",
    "restaurante",
    "cafeteria",
    "cine",
    "teatro",
    "museo",
    "biblioteca",
    "colegio",
    "universidad",
    "hospital",
    "farmacia",
    "aeropuerto",
    "estacion",
    "hotel",
    "gimnasio",
    "piscina",
    "estadio",
    "iglesia",
    "castillo",
    "palacio",
    "puerto",
    "oficina",
    "fabrica",
    "granja",
    "zoo",
    "acuario",
    "circo",
    "discoteca",
    "tienda",
    "peluqueria",
    "banco",
    "gasolinera",
    "parking",
    "carretera",
    "puente",
    "jardin",
    "camping",
  ],
  profesiones: [
    "medico",
    "enfermero",
    "profesor",
    "bombero",
    "policia",
    "abogado",
    "juez",
    "arquitecto",
    "ingeniero",
    "programador",
    "disenador",
    "periodista",
    "fotografo",
    "actor",
    "cantante",
    "musico",
    "pintor",
    "escritor",
    "cocinero",
    "camarero",
    "panadero",
    "mecanico",
    "electricista",
    "fontanero",
    "carpintero",
    "jardinero",
    "agricultor",
    "veterinario",
    "dentista",
    "psicologo",
    "farmaceutico",
    "piloto",
    "azafato",
    "conductor",
    "taxista",
    "repartidor",
    "dependiente",
    "cajero",
    "banquero",
    "contable",
    "economista",
    "cientifico",
    "biologo",
    "astronauta",
    "entrenador",
    "futbolista",
    "bailarin",
    "peluquero",
    "maquillador",
    "traductor",
    "guia turistico",
    "socorrista",
  ],
  "personas-famosas": [
    "Shakira",
    "Messi",
    "Bad Bunny",
    "Rafa Nadal",
    "Einstein",
    "Marie Curie",
    "Michael Jordan",
    "Cristiano Ronaldo",
    "Steve Jobs",
    "Bill Gates",
    "Elon Musk",
    "Freddie Mercury",
    "Pedro Sanchez",
    "Donald Trump",
    "Benjamin Netanyahu",
  ],
  xvip: [
    "Rufino",
    "Esdres",
    "Manolin",
    "Eru Peru",
    "El Calvo",
    "Josema forella",
    "Geranio",
    "El Rase (Sergio)",
    "Jonny el gordo",
  ],
  futbolistas: [
    "Messi",
    "Cristiano Ronaldo",
    "Mbappe",
    "Haaland",
    "Vinicius",
    "Rodrygo",
    "Valverde",
    "Courtois",
    "Camavinga",
    "Tchouameni",
    "Arda Guler",
    "Rodri",
    "Lamine Yamal",
    "Raphinha",
    "Cubarsi",
    "Balde",
    "Araujo",
    "Kounde",
    "Mohamed Salah",
    "Harry Kane",
    "Julian Alvarez",
    "Lautaro Martinez",
    "Cole Palmer",
    "Bukayo Saka",
    "Jamal Musiala",
    "Florian Wirtz",
    "Pedri",
    "Gavi",
    "Dani Olmo",
    "Fermín",
    "Frenkie de Jong",
    "Ferran Torres",
    "Modric",
    "Sergio Ramos",
    "Griezmann",
    "Lewandowski",
    "Neymar",
    "Bellingham",
  ],
};

export const words: Word[] = Object.entries(valuesByCategory).flatMap(
  ([categoryId, values]) =>
    values.map((value, index) => ({
      id: `${categoryId}-${index + 1}`,
      value,
      categoryId,
      locale: "es",
      enabled: true,
    })),
);

export function getEnabledWords(categoryId: string) {
  return words.filter((word) => word.enabled && word.categoryId === categoryId);
}
